export const openEvoScientificState = {
  sourceRepo: 'https://github.com/mykcs/openevo-experiment',
  currentCampaignUrl: 'https://github.com/mykcs/openevo-experiment/blob/main/configs/experiment/current-campaign.json',
  checkedAt: '2026-08-28',
  checkedSourceCommit: '04c0faf02af6f0fcb0724aff3c5697b0c858e9e4',
  defaultBranchSnapshot: {
    branch: 'main',
    campaignId: '20260821-2341-wb1-seed-aligned-webshop-benchmark',
    track: 'Track B - Fair Matched Benchmark',
    phase: 'WB1-TRACKB-CONTINUATION',
    status: 'trackb-gen28-state-v28-adopted-final-locked-no-training',
    title: 'WB1 - Fair Matched WebShop Benchmark (Track B continuation)',
    classification: 'GEN28_STATE_V28_BARRIER_PASS_ADOPTED',
    validCompletedTrainingEpisodes: 3584,
    targetTrainingEpisodes: 20640,
    remainingTrainingEpisodes: 17056,
    cumulativeExactSuccesses: 9,
    latestCompletedGeneration: 28,
    latestNativeStateVersion: 28,
    finalTestStatus: 'locked',
    trainingAllowed: false,
    gpuAllocationAllowed: false,
    formalTaskConsumptionAllowed: false,
  },
  nextGate: {
    zh: 'Gen28 已完成，state-v28 已通过对账并被采纳。当前不允许继续训练、分配 GPU 或解锁最终测试；Gen29 必须经过一次新的执行准备与恢复授权。',
    en: 'Gen28 is complete and state-v28 passed reconciliation and was adopted. Training, GPU allocation, and final-test unlock are not authorized now; Gen29 requires a new execution-readiness and resumption approval.',
  },
  liveStateRule: {
    zh: '要知道“现在到底进行到哪一步”，必须读取真正用于实验的 openevo-experiment 分支，再看该分支的实验总表（current-campaign.json）和最新实验对账 / 结果（reconciliation / result）；只看默认 main 可能会落后。',
    en: 'To resolve the live scientific state, read the openevo-experiment branch actually used for the experiment, then its experiment ledger (current-campaign.json) and latest reconciliation/result. An active scientific branch may be ahead of default main.',
  },
  gpuRule: {
    zh: 'GPU 能不能用不是网页写死的状态。每次启动前都要同时满足实验预注册（preregistration）、明确授权的 GPU UUID（authorized UUIDs）和现场空闲检查；本次核验的默认 main 明确写着 GPU 未授权。',
    en: 'GPU allocation is not a static-site fact. Before every launch, require the experiment preregistration, explicitly authorized GPU UUIDs (authorized UUIDs), and a live-idle check; the checked default main explicitly has GPU allocation disabled.',
  },
} as const;
