import { lazy, Suspense, useState } from 'react';
import { getMessages, localePath, type Locale } from '../../i18n';
import { statusLabel, tierLabel } from '../../lib/format';
import type { AtlasModel } from '../../lib/types';
import type { LandscapeColorBy, LandscapeDimension } from '../../lib/landscape';

const LandscapeD3 = lazy(() => import('./LandscapeD3'));
const LandscapeECharts = lazy(() => import('./LandscapeECharts'));

export default function LandscapePrototype({ models, paperModelIds = [], locale = 'zh' }: { models: AtlasModel[]; paperModelIds?: string[]; locale?: Locale }) {
  const m = getMessages(locale);
  const [engine, setEngine] = useState<'echarts' | 'd3'>('echarts');
  const [view, setView] = useState<'learning' | 'full'>('learning');
  const [onlyPaper, setOnlyPaper] = useState(false);
  const [dimension, setDimension] = useState<LandscapeDimension>('hardware');
  const [colorBy, setColorBy] = useState<LandscapeColorBy>('vendor');
  const filtered = onlyPaper ? models.filter((model) => paperModelIds.includes(model.id)) : models;
  return <div className="landscape-prototype"><div className="landscape-controls" role="group" aria-label={locale === 'zh' ? 'Landscape 视图控制' : 'Landscape view controls'}><button className={`button ${view === 'learning' ? 'is-active' : ''}`} type="button" onClick={() => setView('learning')}>{locale === 'zh' ? '学习视图' : 'Learning view'}</button><button className={`button ${view === 'full' ? 'is-active' : ''}`} type="button" onClick={() => setView('full')}>{locale === 'zh' ? '完整视图' : 'Full view'}</button><label className="check-row"><input type="checkbox" checked={onlyPaper} onChange={(event) => setOnlyPaper(event.target.checked)} />{locale === 'zh' ? '仅显示论文采用模型' : 'Paper-used models only'}</label>{view === 'full' && <><label className="field"><span>{locale === 'zh' ? '纵轴含义' : 'Y-axis meaning'}</span><select value={dimension} onChange={(event) => setDimension(event.target.value as LandscapeDimension)}><option value="hardware">{locale === 'zh' ? '推理资源' : 'Inference resource'}</option><option value="parameters">{locale === 'zh' ? '参数规模' : 'Parameter scale'}</option></select></label><label className="field"><span>{locale === 'zh' ? '颜色含义' : 'Color meaning'}</span><select value={colorBy} onChange={(event) => setColorBy(event.target.value as LandscapeColorBy)}><option value="vendor">{locale === 'zh' ? '厂商 / 家族' : 'Vendor / family'}</option><option value="access">{locale === 'zh' ? '访问方式' : 'Access'}</option><option value="evidence">{locale === 'zh' ? '证据状态' : 'Evidence status'}</option></select></label><div className="engine-switch"><button className={`button ${engine === 'echarts' ? 'is-active' : ''}`} type="button" onClick={() => setEngine('echarts')}>ECharts</button><button className={`button ${engine === 'd3' ? 'is-active' : ''}`} type="button" onClick={() => setEngine('d3')}>D3</button></div></>}</div>{view === 'learning' ? <LearningLandscapeList models={filtered} locale={locale} /> : <><p className="muted landscape-view-note">{locale === 'zh' ? '完整视图允许切换研究含义：纵轴比较推理资源或参数规模，颜色区分厂商、访问方式或证据状态。' : 'Full view lets you switch research meanings: compare inference resources or parameter scale on the Y-axis, and color by vendor, access, or evidence.'}</p><Suspense fallback={<div className="empty-state" role="status">{m.landscape.chartHint}</div>}>{engine === 'echarts' ? <LandscapeECharts models={filtered} locale={locale} dimension={dimension} colorBy={colorBy} /> : <LandscapeD3 models={filtered} locale={locale} dimension={dimension} colorBy={colorBy} />}</Suspense></>}<AccessibleLandscapeTable models={filtered} locale={locale} /></div>;
}

function LearningLandscapeList({ models, locale }: { models: AtlasModel[]; locale: Locale }) {
  return <section className="landscape-learning-list" aria-labelledby="landscape-learning-title"><h2 id="landscape-learning-title">{locale === 'zh' ? '先读懂四个字段' : 'Start with four readable fields'}</h2><p className="muted">{locale === 'zh' ? '学习视图不使用点大小、形状或多重颜色推断；每行只保留研究决策需要的字段。' : 'Learning view avoids inferring meaning from size, shape, or multiple colors; each row keeps only decision-relevant fields.'}</p><div className="landscape-learning-grid">{models.map((model) => <article key={model.id} className="landscape-learning-card"><time dateTime={model.release_date}>{model.release_date}</time><h3><a href={localePath(locale, `/models/${model.id}/`)}>{model.name}</a></h3><p>{model.family} · {model.checkpoint.type}</p><dl><div><dt>{locale === 'zh' ? '推理资源' : 'Inference resource'}</dt><dd>{tierLabel(model.hardware.inference_tier, locale)}</dd></div><div><dt>{locale === 'zh' ? '访问方式' : 'Access'}</dt><dd>{model.openness.weights_available === true ? (locale === 'zh' ? '开放权重' : 'Open weights') : model.access?.api_status === 'available' || model.access?.api_status === 'preview' ? 'API' : (locale === 'zh' ? '待核验' : 'Unknown')}</dd></div><div><dt>{locale === 'zh' ? '证据状态' : 'Evidence'}</dt><dd>{statusLabel(model.data_status, locale)}</dd></div></dl></article>)}</div></section>;
}

function AccessibleLandscapeTable({ models, locale }: { models: AtlasModel[]; locale: Locale }) {
  return <details className="accessible-landscape"><summary>{locale === 'zh' ? '打开可访问表格' : 'Open accessible data table'}</summary><div className="comparison-table-wrap"><table><caption className="sr-only">{locale === 'zh' ? '模型 Landscape 数据' : 'Landscape model data'}</caption><thead><tr><th>{locale === 'zh' ? '模型' : 'Model'}</th><th>{locale === 'zh' ? '发布日期' : 'Release'}</th><th>{locale === 'zh' ? '家族' : 'Family'}</th><th>{locale === 'zh' ? '证据状态' : 'Evidence'}</th></tr></thead><tbody>{models.map((model) => <tr key={model.id}><th scope="row">{model.name}</th><td>{model.release_date}</td><td>{model.family}</td><td>{statusLabel(model.data_status, locale)}</td></tr>)}</tbody></table></div></details>;
}
